// Layout racine de l'application portfolio
// Définit la structure HTML globale, fonts et métadonnées
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// Configuration des polices Google Fonts optimisées
const geistSans = Geist({
  variable: '--font-geist-sans', // Variable CSS pour la police principale
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono', // Variable CSS pour la police monospace
  subsets: ['latin'],
});

// Métadonnées SEO de base (à personnaliser pour le portfolio)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
