// ===================================================================
// LAYOUT RACINE DE L'APPLICATION PORTFOLIO
// ===================================================================
// Définit la structure HTML globale, polices, métadonnées SEO
// ===================================================================
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// Configuration des polices Google Fonts optimisées
const geistSans = Geist({
  variable: '--font-geist-sans', // Variable CSS pour la police principale
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono', // Variable CSS pour la police monospace
  subsets: ['latin'],
});

// Métadonnées SEO de base (à personnaliser pour le portfolio)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        {/* Préconnexion Google Fonts CDN pour améliorer le TTFB des polices */}
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <meta
          name="description"
          content="Portfolio de Donovan GROUT, développeur web full-stack certifié Opquast Expert, spécialisé en accessibilité, performance, SEO et design system. Découvrez mes projets, compétences et recommandations."
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
