// ===================================================================
// LAYOUT RACINE DE L'APPLICATION PORTFOLIO
// ===================================================================
// Définit la structure HTML globale, polices, métadonnées SEO
// ===================================================================
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// Configuration des polices Google Fonts optimisées
const geistSans = Geist({
  variable: '--font-geist-sans', // Variable CSS pour la police principale
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono', // Variable CSS pour la police monospace
  subsets: ['latin'],
});

// Métadonnées SEO de base (à personnaliser pour le portfolio)
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // On gère le nonce uniquement côté client si besoin, sinon on laisse Next/_document injecter le nonce
  let nonce: string | undefined = undefined;
  if (
    typeof window !== 'undefined' &&
    typeof crypto !== 'undefined' &&
    crypto.randomUUID
  ) {
    nonce = crypto.randomUUID();
  }

  return (
    <html lang="fr">
      <head>
        <meta
          name="description"
          content="Portfolio de Donovan GROUT, développeur web full-stack certifié Opquast Expert, spécialisé en accessibilité, performance, SEO et design system. Découvrez mes projets, compétences et recommandations."
        />
        {/* Exemple d'injection de nonce dans un script inline (si besoin) */}
        {/* <script nonce={nonce}>{`console.log('CSP nonce test')`}</script> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        nonce={nonce}
      >
        {children}
      </body>
    </html>
  );
}
